modLoader = "javafml"
loaderVersion = "[40,)"
license = "LGPL-3.0-or-later"

[[mods]]
modId = "pvptoggle"
version = "${version}"
displayName = "Pvp Toggle"
displayURL="https://github.com/manyrandomthings/pvp-toggle"
authors="manyrandomthings"
description = '''
Makes pvp toggleable
'''

[[dependencies.pvptoggle]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "SERVER"

[[dependencies.pvptoggle]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "SERVER"
